### ISSUE TITLE
typo in url on releases page

### ISSUE THREAD

**Issue by chr1swallace** [pachterlab/kallisto-transcriptome-indices#1]
Your page https://github.com/pachterlab/kallisto-transcriptome-indices/releases contains the url 

ftp://ftp.ensembl.org/pub/release-t5/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.75.cdna.abinitio.fa.gz

which I think should be 

ftp://ftp.ensembl.org/pub/release-75/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh37.75.cdna.abinitio.fa.gz

[ s/release-t5/release-75/ ]

**Comment by Munfred** [comment]
Good catch! Fixed it, thanks
