### ISSUE TITLE
genome or transcriptome for index?

### ISSUE THREAD

**Issue by yeroslaviz** [pachterlab/kallisto-transcriptome-indices#10]
I know kallisto works with the transcriptome and not genome. 

As you don't have the indexed genome for Drosophila yet for the newer version of kallisto I would like to create it myself. 

I was wondering if one needs to do it with the transcriptome (cdna) or with the genome (dna) fasta files. In your README, the links you posted are all the genomic sequences, so I'm not sure, which one is the right one.

your advice will be appreciated.

**Comment by Yenaled** [comment]
This indices were created by kb-python: kb-python takes in the GENOME fasta and extracts a TRANSCRIPTOME fasta from it (and then calls the 'kallisto index' command on the TRANSCRIPTOME fasta that it just extracted).

If you don't use kb-python and simply stick with calling the 'kallisto index' command, then you should be using the TRANSCRIPTOME fasta. The 'kallisto index' commands always uses the TRANSCRIPTOME fasta.
