### ISSUE TITLE
Missing Linnarsson index

### ISSUE THREAD

**Issue by ethanweinberger** [pachterlab/kallisto-transcriptome-indices#11]
Hello! I'm attempting to work through the kallisto | bustools RNA velocity tutorial notebook at https://www.kallistobus.tools/tutorials/kb_velocity/python/kb_velocity/ (Colab version [here](https://colab.research.google.com/github/pachterlab/kallistobustools/blob/master/docs/tutorials/kb_velocity/python/kb_velocity.ipynb)). One of the cells in the tutorial notebook attempts to download a prebuilt RNA velocity index from this repository via the command

`kb ref -d linnarsson -i index.idx -g t2g.txt -c1 spliced_t2c.txt -c2 unspliced_t2c.txt`

This command searches for a tar file located at https://github.com/pachterlab/kallisto-transcriptome-indices/releases/download/v1/linnarsson_index_standard.tar.xz. However, this file appears to be missing and thus the command fails with a 404 error. Has the file been move somewhere else?

Thanks in advance.

**Comment by Yenaled** [comment]
The file no longer exists and we no longer use the linnarson index (you can still build it manually using an older version of kb-python). The velocity notebook is out of date and we are working on a new manual.

**Comment by ethanweinberger** [comment]
Thanks so much for the super quick response @Yenaled! After opening the issue here I found a [related issue](https://github.com/pachterlab/kb_python/issues/228) on the `kb_python` repository, and so I'll close this issue and follow your instructions there.

Thanks for the great tool.
