### ISSUE TITLE
Transcript version number in t2g.py

### ISSUE THREAD

**Issue by ag1805x** [pachterlab/kallisto-transcriptome-indices#3]
I have successfully built index for GRCh38 release-97. Next I was trying to create transcripts_to_genes file with the t2g.py script given here, but it doesn't return the version number even with the -v option on.

**Comment by ag1805x** [comment]
> I have successfully built index for GRCh38 release-97. Next I was trying to create transcripts_to_genes file with the t2g.py script given here, but it doesn't return the version number even with the -v option on.


I found an alternate way to generate this:
```
zcat Homo_sapiens.GRCh38.cdna.all.fa.gz | grep '>' | cut -d ' ' -f1,4,7 > temp
paste <(cut -d '>' -f2 temp | cut -d ' ' -f1) <(cut -d ' ' -f2 temp | cut -d ':' -f2) <(cut -d ' ' -f3 temp | cut -d ':' -f2) >> tx2gene.txt
rm temp
```

**Comment by LouisFaure** [comment]
That is because the two following lines are commented:


```
# tid += '.' + d['transcript_version']
# gid += '.' + d['gene_version']
```

uncommenting these solve the issue

**Comment by ag1805x** [comment]
> That is because the two following lines are commented:
> 
> ```
> # tid += '.' + d['transcript_version']
> # gid += '.' + d['gene_version']
> ```
> 
> uncommenting these solve the issue

I thought the same thing and removed those `#` but it throws up a different error.

```
File "./t2g.py", line 35
    tid += '.' + d['transcript_version']
                                       ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by LouisFaure** [comment]
You need to remove the space after # as well

**Comment by ag1805x** [comment]
> You need to remove the space after # as well

Thank you. It did finally work.
