### ISSUE TITLE
Indices downloaded through command line outdated

### ISSUE THREAD

**Issue by shashkat** [pachterlab/kallisto-transcriptome-indices#8]
Hi, I observed that the indices which are downloaded using this command:
```
kb ref -d zebrafish -i index.idx -g t2g.txt
```
appear to be outdated. They give this output with kallisto quant command on kallisto version 0.50.1. 
```
Error: incompatible indices. Found version 10, expected version 13
Rerun with index to regenerate%
```

I believe that shouldn't be the case, as the ones on the releases page (at the very top of the Readme) are updated. Hence, I thought to inform.

Anyways, thanks for making this awesome tool!

**Comment by Yenaled** [comment]
Works fine on my end with kb-python 0.28.0.

**Comment by shashkat** [comment]
Ohh okay, thanks for confirming! Probably the error is due to my kallisto which was installed using brew.
