### ISSUE TITLE
Do the prebuilt indexes contain ncRNA?

### ISSUE THREAD

**Issue by st4302** [pachterlab/kallisto-transcriptome-indices#9]
Do the v1 prebuilt indexes from  https://github.com/pachterlab/kallisto-transcriptome-indices/releases and the t2g files contain ncRNA?

Thank you

**Comment by Yenaled** [comment]
Look at the README -- it shows all everything that's included (lncRNAs but not other types of ncRNAs). Also, it states please post issues on the main kallisto/kb-python repo, not here.
